In [2]:
import copy, math
import numpy as np
import matplotlib.pyplot as plt
np.set_printoptions(precision=2)

In [3]:
X_train = np.array([[2104, 5, 1, 45], [1416, 3, 2, 40], [852, 2, 1, 35]])
y_train = np.array([460, 232, 178])

In [4]:
print(f"X Shape: {X_train.shape}, X Type:{type(X_train)})")
print(X_train)
print(f"y Shape: {y_train.shape}, y Type:{type(y_train)})")
print(y_train)

X Shape: (3, 4), X Type:<class 'numpy.ndarray'>)
[[2104    5    1   45]
 [1416    3    2   40]
 [ 852    2    1   35]]
y Shape: (3,), y Type:<class 'numpy.ndarray'>)
[460 232 178]


In [5]:
b_init = 785.1811367994083
w_init = np.array([ 0.39133535, 18.75376741, -53.36032453, -26.42131618])
print(f"w_init shape: {w_init.shape}, b_init type: {type(b_init)}")

w_init shape: (4,), b_init type: <class 'float'>


In [6]:
def predict_single_loop(x, w, b):
    n = x.shape[0]
    p = 0
    for i in range(n):
        p_i = x[i] * w[i]
        p = p + p_i
    p = p + b
    return p

In [7]:
x_vec = X_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")
f_wb = predict_single_loop(x_vec, w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083


In [9]:
def predict(x, w, b):
    p = np.dot(x, w) + b
    return p

In [11]:
x_vec = X_train[0,:]
print(f"x_vec shape {x_vec.shape}, x_vec value: {x_vec}")
f_wb = predict(x_vec,w_init, b_init)
print(f"f_wb shape {f_wb.shape}, prediction: {f_wb}")

x_vec shape (4,), x_vec value: [2104    5    1   45]
f_wb shape (), prediction: 459.9999976194083


In [12]:
def compute_cost(X, y, w, b):
    m = X.shape[0]
    cost = 0.0
    for i in range(m):
        f_wb_i = np.dot(X[i], w) + b           #(n,)(n,) = scalar (see np.dot)
        cost = cost + (f_wb_i - y[i])**2       #scalar
    cost = cost / (2 * m)                      #scalar
    return cost

In [13]:
cost = compute_cost(X_train, y_train, w_init, b_init)
print(f'Cost at optimal w : {cost}')

Cost at optimal w : 1.5578904428966628e-12


In [14]:
def compute_gradient(X, y, w, b):
    m,n = X.shape
    dj_dw = np.zeros((n,))
    dj_db = 0.

    for i in range(m):
        err = (np.dot(X[i], w) + b) - y[i]
        for j in range(n):
            dj_dw[j] = dj_dw[j] + err * X[i, j]
        dj_db = dj_db + err
    dj_dw = dj_dw / m
    dj_db = dj_db / m

    return dj_db, dj_dw

In [15]:
tmp_dj_db, tmp_dj_dw = compute_gradient(X_train, y_train, w_init, b_init)
print(f'dj_db at initial w,b: {tmp_dj_db}')
print(f'dj_dw at initial w,b: \n {tmp_dj_dw}')

dj_db at initial w,b: -1.6739251501955248e-06
dj_dw at initial w,b: 
 [-2.73e-03 -6.27e-06 -2.22e-06 -6.92e-05]


In [16]:
def gradient_descent(X, y, w_in, b_in, cost_function, gradient_function, alpha, num_iters):
    J_history = []
    w = copy.deepcopy(w_in)
    b = b_in

    for i in range(num_iters):
        dj_db,dj_dw = gradient_function(X, y, w, b)
        w = w - alpha * dj_dw
        b = b - alpha * dj_db

        if i<100000:
            J_history.append( cost_function(X, y, w, b))

        if i% math.ceil(num_iters / 10) == 0:
            print(f"Iteration {i:4d}: Cost {J_history[-1]:8.2f}   ")

    return w, b, J_history

In [17]:
initial_w = np.zeros_like(w_init)
initial_b = 0.
iterations = 1000
alpha = 5.0e-7
w_final, b_final, J_hist = gradient_descent(X_train, y_train, initial_w, initial_b,
                                                    compute_cost, compute_gradient,
                                                    alpha, iterations)
print(f"b,w found by gradient descent: {b_final:0.2f},{w_final} ")
m,_ = X_train.shape
for i in range(m):
    print(f"prediction: {np.dot(X_train[i], w_final) + b_final:0.2f}, target value: {y_train[i]}")

Iteration    0: Cost  2529.46   
Iteration  100: Cost   695.99   
Iteration  200: Cost   694.92   
Iteration  300: Cost   693.86   
Iteration  400: Cost   692.81   
Iteration  500: Cost   691.77   
Iteration  600: Cost   690.73   
Iteration  700: Cost   689.71   
Iteration  800: Cost   688.70   
Iteration  900: Cost   687.69   
b,w found by gradient descent: -0.00,[ 0.2   0.   -0.01 -0.07] 
prediction: 426.19, target value: 460
prediction: 286.17, target value: 232
prediction: 171.47, target value: 178


In [19]:
import os
import shutil # Added for copying files
from google.colab import drive
from google.colab import userdata
GITHUB_TOKEN = userdata.get('GITHUB_TOKEN')

# Mount Google Drive if not already mounted
if not os.path.exists('/content/drive'):
    drive.mount('/content/drive')
else:
    print('Google Drive already mounted.')

# --- FILL THESE IN ONCE ---
GITHUB_USERNAME = "notlokii"
REPO_NAME       = "AndrewNgMLCourse_Self-Coded_Labs"

# --- CHANGE THIS EVERY NOTEBOOK ---
NOTEBOOK_FILENAME = "week2_multiple_linear_regression.ipynb"   # rename each time
COMMIT_MESSAGE    = "week 2: multiple linear regression implemented from scratch"

# --- DON'T TOUCH BELOW ---
REPO_URL = f"https://{GITHUB_USERNAME}:{GITHUB_TOKEN}@github.com/{GITHUB_USERNAME}/{REPO_NAME}.git"

# Assume a standard path for notebooks saved in Google Drive
source_notebook_path = f"/content/drive/MyDrive/Colab Notebooks/{NOTEBOOK_FILENAME}"

# Define the target path in the /content directory for git operations
target_notebook_path = f"/content/{NOTEBOOK_FILENAME}"

try:
    if os.path.exists(source_notebook_path):
        shutil.copy(source_notebook_path, target_notebook_path)
        print(f"Notebook copied from '{source_notebook_path}' to '{target_notebook_path}'")
    else:
        print(f"Error: Source notebook not found at '{source_notebook_path}'. Please ensure the notebook is saved in MyDrive/Colab Notebooks/.")
        # You might want to raise an error or exit here if the file is critical
except Exception as e:
    print(f"An unexpected error occurred during file copy: {e}")

# clone repo, add notebook, commit, push
!git config --global user.email "lokeshrp2007@gmail.com"
!git config --global user.name "{GITHUB_USERNAME}"

!git clone {REPO_URL} /content/repo 2>/dev/null || echo "already cloned"

# Navigate to the repository directory and pull with rebase to handle divergent branches
!cd /content/repo && git pull --rebase origin main

# Use the correctly copied notebook path
!cp {target_notebook_path} /content/repo/
!cd /content/repo && git add {NOTEBOOK_FILENAME}
!cd /content/repo && git commit -m "{COMMIT_MESSAGE}"
!cd /content/repo && git push origin main

print(f"\n✅ '{NOTEBOOK_FILENAME}' pushed to GitHub successfully!")

Mounted at /content/drive
Notebook copied from '/content/drive/MyDrive/Colab Notebooks/week2_multiple_linear_regression.ipynb' to '/content/week2_multiple_linear_regression.ipynb'
From https://github.com/notlokii/AndrewNgMLCourse_Self-Coded_Labs
 * branch            main       -> FETCH_HEAD
Already up to date.
[main 3c634f1] week 2: multiple linear regression implemented from scratch
 1 file changed, 1 insertion(+)
 create mode 100644 week2_multiple_linear_regression.ipynb
Enumerating objects: 4, done.
Counting objects: 100% (4/4), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 37.62 KiB | 7.52 MiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/notlokii/AndrewNgMLCourse_Self-Coded_Labs.git
   be01552..3c634f1  main -> main

✅ 'week2_multiple_linear_regression.ipynb' pushed to GitHub successfully!
